name: CI/CD - Build & Push to ECR

on:
  push:
    branches:
      - main

jobs:
  Continues-Integration_build_and_push:
    runs-on: ubuntu-latest

    steps:
      - name: 🧾 Checkout code
        uses: actions/checkout@v3
        with:
          repository: AdaEde22/green-special-frontend
          ref: main

      - name: 🔧login into AWSCLI 
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Build container image
        run: docker build -t AdaEde22/green-special-frontend:latest 


      - name:  Login to Amazon ECR with short lived credentials
        run: |
         aws-aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin ${{ vars.ECR_REPO }}
         actions/amazon-ecr-login@v2
     
      - name: Tag Docker image
        run: docker tag green-special-frontend:latest ${{ vars.ECR_REPO }}/green-special-frontend:${{ github.run_number }}
    

      

      # - name:  Build Docker image
      #   run: |
      #     docker build -t ${{ secrets.ECR_REPOSITORY }}:latest .

      # - name: Tag image with ECR URL
      #   run: |
      #     docker tag ${{ secrets.ECR_REPOSITORY }}:latest ${{ secrets.ECR_REGISTRY }}/${{ secrets.ECR_REPOSITORY }}:latest

      # - name: Push Docker image to ECR
      #   run: |
      #    docker push ${{ secrets.ECR_REGISTRY }}/green-special-frontend:${{ secrets.ECR_REPOSITORY }}:latest
      - name: Push image to ECR
        run: docker push ${{ vars.ECR_REPO }}/green-special-frontend:${{ github.run_number }}

      - name: Clean up Docker image locally
        run: |
         docker rmi green-special-frontend:latest
         docker rmi ${{ vars.ECR_REPO }}/green-special-frontend:${{ github.run_number }}

      - name: Clean up GitHub repo on runner
        run: rm -rf ./*

Continues-Update_k8s_manifest:
    runs-on: ubuntu-latest
    needs: Continues-Integration_build_and_push
    steps:
    - name: Checkout repository.
      env:
          GIT_USERNAME: ${{ secrets.GIT_USERNAME }}
          GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
      run: |
         git clone https://${GIT_USERNAME}:${GIT_PASSWORD}@github.com/Adaede22/kubernetes-manifest1.git
         
         cd kubernetes-manifest1
         git config --global user.email "jnoyima@gmail.com"
         git config --global user.name "AdaEde22"

         sed -i "s+${{ vars.ECR_REPO }}/green-special-frontend:.*+${{ vars.ECR_REPO }}/green-special-frontend:${{ github.run_number }}+g" ./bank-project/frontend.yaml

         cat ./Green-special/frontend.yaml | grep -q "${{ vars.ECR_REPO }}/green-special-frontend:${{ github.run_number }}"

         git add GREEN_SPECIAL/frontend.yaml
         git commit -m "Update frontend image to version ${{ github.run_number }}"
         git push origin main

